### ISSUE TITLE
Implement missing unique_field() in HiveCredentials class

### ISSUE THREAD

**Issue by niteshy** [cloudera/dbt-hive#136]
All tests are broken after upgrading dbt-core to 1.5.10 because of missing unique_field() method in HiveCredentials class. As it is essential to setup the connections 

```
Invoking dbt with ['seed']
20:53:09  Running with dbt=1.5.10
20:53:09  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'True', 'fail_fast': 'False', 'log_path': '/home/nitesh/code/cloudera/dbt/dbt-hive/logs/test17115727864964321969', 'version_check': 'True', 'profiles_dir': '/tmp/pytest-of-nitesh/pytest-1/profile0', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'False'}
20:53:09  Connection '_test' was properly closed.
20:53:09  Encountered an error:
unique_field not implemented for base credentials class
20:53:09  Traceback (most recent call last):
  File "/home/nitesh/code/cloudera/dbt/dbt-hive/.venv1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/nitesh/code/cloudera/dbt/dbt-hive/.venv1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/home/nitesh/code/cloudera/dbt/dbt-hive/.venv1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/home/nitesh/code/cloudera/dbt/dbt-hive/.venv1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/nitesh/code/cloudera/dbt/dbt-hive/.venv1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 203, in wrapper
    config.credentials.hashed_unique_field()
  File "/home/nitesh/code/cloudera/dbt/dbt-hive/.venv1.5/lib/python3.8/site-packages/dbt/contracts/connection.py", line 144, in hashed_unique_field
    return md5(self.unique_field)
  File "/home/nitesh/code/cloudera/dbt/dbt-hive/.venv1.5/lib/python3.8/site-packages/dbt/contracts/connection.py", line 141, in unique_field
    raise NotImplementedError("unique_field not implemented for base credentials class")
NotImplementedError: unique_field not implemented for base credentials class

20:53:09  Command `cli seed` failed at 13:53:09.839696 after 0.01 seconds
20:53:09  Flushing usage events
FAILED
````

**Comment by niteshy** [comment]
Resolved by https://github.com/cloudera/dbt-hive/pull/137
